/**
 * Seed Kuwait City Raw Materials from Spreadsheet Data
 * Uploads raw material data with initial stock quantity = 0
 * 
 * Usage: node backend/scripts/seedKuwaitCityFromSpreadsheet.js
 */

const connectKuwaitCityDB = require('../config/kuwaitCityDB');
const { initializeKuwaitCityModels } = require('../models/kuwaitCityModels');

// Raw material data from spreadsheet
const rawMaterialsData = [
  { name: "All Spicy Ground", price: 0, sku: "10000", category: "SPICES" },
  { name: "Almond Flour", price: 0, sku: "10001", category: "PANTRY" },
  { name: "Almond Milk", price: 0, sku: "10002", category: "DIARY" },
  { name: "Almond Slices", price: 0, sku: "10003", category: "DIARY" },
  { name: "Almond Whole", price: 0, sku: "10004", category: "PANTRY" },
  { name: "Apple Cider Vinegar", price: 0, sku: "10005", category: "SAUCE & VINEGAR" },
  { name: "Arabic Bread", price: 0, sku: "10006", category: "BREAD" },
  { name: "Arabic Brown Bread", price: 0, sku: "10007", category: "BREAD" },
  { name: "Arborio Rice", price: 0, sku: "10008", category: "RICE" },
  { name: "Artichoke Hearts", price: 0, sku: "10009", category: "HOT & COLD SECTION" },
  { name: "Arugula", price: 0, sku: "10010", category: "FRUIT & VEGETABLES" },
  { name: "Asparagus", price: 0, sku: "10011", category: "FRUIT & VEGETABLES" },
  { name: "Avocado", price: 0, sku: "10012", category: "FRUIT & VEGETABLES" },
  { name: "Baby Carrot", price: 0, sku: "10013", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Baby Corn", price: 0, sku: "10014", category: "FRUIT & VEGETABLES" },
  { name: "Baby Potato", price: 0, sku: "10015", category: "FRUIT & VEGETABLES" },
  { name: "Baby Spinach", price: 0, sku: "10016", category: "FRUIT & VEGETABLES" },
  { name: "Baked Beans", price: 0, sku: "10017", category: "CARBS" },
  { name: "Baking Flour", price: 0, sku: "10018", category: "FLOUR", unit: "kg" },
  { name: "Baking Powder", price: 0, sku: "10019", category: "SPICES" },
  { name: "Baking Soda", price: 0, sku: "10020", category: "HOT & COLD SECTION", unit: "kg" },
  { name: "Balsamic Crema", price: 0, sku: "10021", category: "SAUCE & VINEGAR" },
  { name: "Balsamic Vinegar", price: 0, sku: "10022", category: "SAUCE & VINEGAR" },
  { name: "Banana", price: 0, sku: "10023", category: "FRUIT & VEGETABLES" },
  { name: "Barberry", price: 0, sku: "10024", category: "FRUIT & VEGETABLES" },
  { name: "Basil", price: 0, sku: "10025", category: "FRUIT & VEGETABLES" },
  { name: "Basmati Rice", price: 0, sku: "10026", category: "RICE" },
  { name: "Bay Leaves", price: 0, sku: "10027", category: "FRUIT & VEGETABLES" },
  { name: "Bbq Magic Powder", price: 0, sku: "10028", category: "SPICES" },
  { name: "Bbq Sauce", price: 0, sku: "10029", category: "SAUCE & VINEGAR" },
  { name: "Bbq Seasoning", price: 0, sku: "10030", category: "SPICES" },
  { name: "Beef Brisket Cab", price: 0, sku: "10031", category: "MEAT" },
  { name: "Beef Striploin", price: 0, sku: "10032", category: "MEAT" },
  { name: "Beef Tenderloin", price: 0, sku: "10033", category: "MEAT" },
  { name: "Beet Root Diced Can", price: 0, sku: "10034", category: "FRUIT & VEGETABLES" },
  { name: "Beetroot", price: 0.450, sku: "10035", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Beetroot - Sliced", price: 0, sku: "10036", category: "FRUIT & VEGETABLES" },
  { name: "Bhujia", price: 0, sku: "10037", category: "BAKERY" },
  { name: "Biryani Masala", price: 0, sku: "10038", category: "SPICES" },
  { name: "Black Beans", price: 0, sku: "10039", category: "CARBS" },
  { name: "Black Berry", price: 0, sku: "10040", category: "FRUIT & VEGETABLES" },
  { name: "Black Eye Beans", price: 0, sku: "10041", category: "CARBS" },
  { name: "Black Grape", price: 0, sku: "10042", category: "FRUIT & VEGETABLES" },
  { name: "Black Olive Sliced", price: 0, sku: "10043", category: "CARBS" },
  { name: "Black Pepper Powder", price: 0, sku: "10044", category: "SPICES" },
  { name: "Black Pepper Whole", price: 0, sku: "10045", category: "SPICES" },
  { name: "Black Rice", price: 0, sku: "10046", category: "RICE" },
  { name: "Black Salt", price: 0, sku: "10047", category: "HOT & COLD SECTION" },
  { name: "Blue Berry", price: 0, sku: "10048", category: "FRUIT & VEGETABLES" },
  { name: "Bran Flakes", price: 0, sku: "10049", category: "BAKERY" },
  { name: "Bread Crumbs", price: 0, sku: "10050", category: "HOT & COLD SECTION" },
  { name: "Bread Improver", price: 0, sku: "10051", category: "BAKERY" },
  { name: "Brie Cheese", price: 0, sku: "10052", category: "CHEESE & BUTTER" },
  { name: "Broccoli", price: 0, sku: "10053", category: "FRUIT & VEGETABLES" },
  { name: "Brown Burger Bun Plain 2.5 Inch (Small)", price: 0, sku: "10054", category: "BREAD" },
  { name: "Brown Burger Bun Plain 4 Inch (Big)", price: 0, sku: "10055", category: "BREAD" },
  { name: "Brown Burger Bun With Mix Seeds On Top 4 Inch", price: 0, sku: "10056", category: "BREAD" },
  { name: "Brown Burger Bun With Oats On Top 4 Inch", price: 0, sku: "10057", category: "BREAD" },
  { name: "Brown Ciabatta 7 Inch With Mix Seeds", price: 0, sku: "10058", category: "BREAD" },
  { name: "Brown Ciabatta Bread 7 Inch", price: 0, sku: "10059", category: "BREAD" },
  { name: "Brown Flour", price: 0, sku: "10060", category: "FLOUR" },
  { name: "Brown Hoagie With Mix Seeds On Top", price: 0, sku: "10061", category: "BREAD" },
  { name: "Brown Kraft Sandwich", price: 0, sku: "10062", category: "NON FOOD - PACKING" },
  { name: "Brown Rice Basmati", price: 0, sku: "10063", category: "RICE" },
  { name: "Brown Spaghetti Natureland", price: 0, sku: "10064", category: "PASTA" },
  { name: "Brown Sugar Dark", price: 0, sku: "10065", category: "SUGAR" },
  { name: "Brown Sugar Light", price: 0, sku: "10066", category: "SUGAR" },
  { name: "Brown Bread Toast", price: 0, sku: "10067", category: "BREAD", unit: "kg" },
  { name: "Brown Toast Slice", price: 0, sku: "10068", category: "BREAD" },
  { name: "Buffalo Wing Sauce", price: 0, sku: "10069", category: "SAUCE & VINEGAR" },
  { name: "Burgul Rice", price: 0, sku: "10070", category: "RICE" },
  { name: "Butter Anchor", price: 0, sku: "10071", category: "CHEESE & BUTTER" },
  { name: "Butter Block", price: 0, sku: "10072", category: "CHEESE & BUTTER" },
  { name: "Butter President", price: 0, sku: "10073", category: "CHEESE & BUTTER" },
  { name: "Butter President Portion", price: 0, sku: "10074", category: "CHEESE & BUTTER" },
  { name: "Butter-Head Lettuce", price: 0, sku: "10075", category: "FRUIT & VEGETABLES" },
  { name: "Button Mushrom", price: 0, sku: "10076", category: "FRUIT & VEGETABLES" },
  { name: "Cajun Seasoning", price: 0, sku: "10077", category: "SPICES" },
  { name: "Capers In Vinegar", price: 0, sku: "10078", category: "HOT & COLD SECTION" },
  { name: "Caramel Syrup", price: 0, sku: "10079", category: "BAKERY" },
  { name: "Caraway Seeds", price: 0, sku: "10080", category: "HOT & COLD SECTION" },
  { name: "Cardamom Powder", price: 0, sku: "10081", category: "SPICES" },
  { name: "Cardamom Whole Jumbo", price: 0, sku: "10082", category: "SPICES" },
  { name: "Carlex Spray", price: 0, sku: "10083", category: "HOT & COLD SECTION" },
  { name: "Carrot", price: 0, sku: "10084", category: "FRUIT & VEGETABLES" },
  { name: "Purple Carrot", price: 0, sku: "10085", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Cashew Whole", price: 0, sku: "10086", category: "PANTRY" },
  { name: "Cauliflower", price: 0, sku: "10087", category: "FRUIT & VEGETABLES" },
  { name: "Cayenne Pepper", price: 0, sku: "10088", category: "SPICES" },
  { name: "Celery", price: 0, sku: "10089", category: "FRUIT & VEGETABLES" },
  { name: "Chana Dal", price: 0, sku: "10090", category: "HOT & COLD SECTION" },
  { name: "Cheddar Yellow", price: 0, sku: "10091", category: "CHEESE & BUTTER" },
  { name: "Cheder Cheese Slice", price: 0, sku: "10092", category: "CHEESE & BUTTER" },
  { name: "Cherry Tomato - Red", price: 0, sku: "10093", category: "FRUIT & VEGETABLES" },
  { name: "Cherry Tomato - Yellow", price: 0, sku: "10094", category: "FRUIT & VEGETABLES" },
  { name: "Chia Seed", price: 0, sku: "10095", category: "PANTRY" },
  { name: "Chick Peas", price: 0, sku: "10096", category: "CRABS" },
  { name: "Chick Peas Maxican", price: 0, sku: "10097", category: "HOT & COLD SECTION" },
  { name: "Chicken Breast", price: 0, sku: "10098", category: "CHICKEN" },
  { name: "Chicken Breast - Alyoum", price: 0, sku: "10099", category: "CHICKEN" },
  { name: "Chicken Breast Uncalibrated", price: 0, sku: "10100", category: "CHICKEN" },
  { name: "Chicken Maggi Cubes", price: 0, sku: "10101", category: "SPICES" },
  { name: "Chicken Mix Spices", price: 0, sku: "10102", category: "SPICES" },
  { name: "Chicken Whole Brazil", price: 0, sku: "10103", category: "CHICKEN" },
  { name: "Chipotle Chilli Powder", price: 0, sku: "10104", category: "SPICES" },
  { name: "Chives", price: 0, sku: "10105", category: "FRUIT & VEGETABLES" },
  { name: "Ciabatta Oregano Brown", price: 0, sku: "10106", category: "BREAD" },
  { name: "Ciabatta Square", price: 0, sku: "10107", category: "BREAD" },
  { name: "Cinamon Stick", price: 0, sku: "10108", category: "SPICES" },
  { name: "Cinnamon Powder", price: 0, sku: "10109", category: "SPICES" },
  { name: "Clear Microcontainer 2 Comp", price: 0, sku: "10110", category: "NON FOOD - PACKING" },
  { name: "Clear Plastic Bag", price: 0, sku: "10111", category: "NON FOOD - PACKING" },
  { name: "Clear Sauce Cup", price: 0, sku: "10112", category: "NON FOOD - PACKING" },
  { name: "Clear Square Juice Bottl", price: 0, sku: "10113", category: "NON FOOD - PACKING" },
  { name: "Cloves", price: 0, sku: "10114", category: "SPICES" },
  { name: "Cocoa Powder", price: 0, sku: "10115", category: "BAKERY" },
  { name: "Coconut Desiccated Powder", price: 0, sku: "10116", category: "BAKERY" },
  { name: "Coconut Flaks", price: 0, sku: "10117", category: "BAKERY" },
  { name: "Coconut Flour", price: 0, sku: "10118", category: "FLOUR" },
  { name: "Coconut Milk Can", price: 0, sku: "10119", category: "HOT & COLD SECTION" },
  { name: "Coconut Milk Powder", price: 0, sku: "10120", category: "HOT & COLD SECTION" },
  { name: "Coconut Oil", price: 0, sku: "10121", category: "OIL" },
  { name: "Coconut Sugar", price: 0, sku: "10122", category: "SUGAR" },
  { name: "Condensed Milk", price: 0, sku: "10123", category: "DIARY" },
  { name: "Cooking Cream", price: 0, sku: "10124", category: "DIARY" },
  { name: "Coriander Leaves", price: 0, sku: "10125", category: "FRUIT & VEGETABLES" },
  { name: "Coriander Powder", price: 0, sku: "10126", category: "SPICES" },
  { name: "Coriander Seeds", price: 0, sku: "10127", category: "SPICES" },
  { name: "Corn Flour Maize Starch", price: 0, sku: "10128", category: "HOT & COLD SECTION" },
  { name: "Corn Oil", price: 0, sku: "10129", category: "OIL" },
  { name: "Corn On The Cob Frozen", price: 0, sku: "10130", category: "FROZEN VEG&FRUITS" },
  { name: "Cous Cous", price: 0, sku: "10131", category: "BAKERY" },
  { name: "Cranberry", price: 0, sku: "10132", category: "PANTRY" },
  { name: "Cream Caramel Powder", price: 0, sku: "10133", category: "BAKERY" },
  { name: "Cream Cheese", price: 0, sku: "10134", category: "DIARY" },
  { name: "Cream Of Tartar", price: 0, sku: "10135", category: "DIARY" },
  { name: "Creamdori Fish Fillet", price: 0, sku: "10136", category: "SEAFOOD" },
  { name: "Cucumber", price: 0, sku: "10137", category: "FRUIT & VEGETABLES" },
  { name: "Cucumber Whole Pickle Gallon", price: 0, sku: "10138", category: "HOT & COLD SECTION" },
  { name: "Cumin Powder", price: 0, sku: "10139", category: "SPICES" },
  { name: "Cumin Seeds", price: 0, sku: "10140", category: "SPICES" },
  { name: "Curry Leaves", price: 0, sku: "10141", category: "FRUIT & VEGETABLES" },
  { name: "Curry Powder", price: 0, sku: "10142", category: "SPICES" },
  { name: "Cut Pistacho", price: 0, sku: "10143", category: "PANTRY" },
  { name: "Cutlery Set", price: 0, sku: "10144", category: "NON FOOD - PACKING" },
  { name: "Dami Glace Maggi", price: 0, sku: "10145", category: "BAKERY" },
  { name: "Dark Chocolate Coins", price: 0, sku: "10146", category: "BAKERY" },
  { name: "Date Khodare", price: 0, sku: "10147", category: "BAKERY" },
  { name: "Date Paste", price: 0, sku: "10148", category: "BAKERY" },
  { name: "Date Sokare", price: 0, sku: "10149", category: "BAKERY" },
  { name: "Demi Glace Maggi", price: 0, sku: "10150", category: "HOT & COLD SECTION" },
  { name: "Digestive Biscuit", price: 0, sku: "10151", category: "BAKERY" },
  { name: "Dijon Mustard", price: 0, sku: "10152", category: "HOT & COLD SECTION" },
  { name: "Dill", price: 0, sku: "10153", category: "FRUIT & VEGETABLES" },
  { name: "Doritos Nacho Cheese", price: 0, sku: "10154", category: "CHEESE & BUTTER" },
  { name: "Dry Apricot", price: 0, sku: "10155", category: "PANTRY" },
  { name: "Dry Basil Leaves", price: 0, sku: "10156", category: "SPICES" },
  { name: "Dry Canberry", price: 0, sku: "10157", category: "PANTRY" },
  { name: "Dry Khudri Black Dates", price: 0, sku: "10158", category: "BAKERY" },
  { name: "Dry Lemon", price: 0, sku: "10159", category: "SPICES" },
  { name: "Dry Mint Leaves", price: 0, sku: "10160", category: "SPICES" },
  { name: "Dry Oregano", price: 0, sku: "10161", category: "SPICES" },
  { name: "Dry Red Chilly", price: 0, sku: "10162", category: "SPICES" },
  { name: "Dry Yeast", price: 0, sku: "10163", category: "HOT & COLD SECTION" },
  { name: "Edamame", price: 0, sku: "10164", category: "FROZEN VEG&FRUITS" },
  { name: "Edamame Soya Beans Peeled", price: 0, sku: "10165", category: "FROZEN VEG&FRUITS" },
  { name: "Edamame With Shell", price: 0, sku: "10166", category: "FROZEN VEG&FRUITS" },
  { name: "Egg", price: 0, sku: "10167", category: "BAKERY" },
  { name: "Egg Replacer", price: 0, sku: "10168", category: "BAKERY" },
  { name: "Eggplant", price: 0, sku: "10169", category: "FRUIT & VEGETABLES" },
  { name: "Egyptian Rice", price: 0, sku: "10170", category: "RICE" },
  { name: "Elle & Vire", price: 0, sku: "10171", category: "DIARY" },
  { name: "Emanthal Cheese", price: 0, sku: "10172", category: "CHEESE & BUTTER" },
  { name: "Fajita Magic Powder Inch", price: 0, sku: "10173", category: "SPICES" },
  { name: "Fajita Magic Powder Inch Usa", price: 0, sku: "10174", category: "SPICES" },
  { name: "Farfalle Pasta", price: 0, sku: "10175", category: "PASTA" },
  { name: "Fennel Seeds", price: 0, sku: "10176", category: "SPICES" },
  { name: "Fenugreek Leaves", price: 0, sku: "10177", category: "SPICES" },
  { name: "Fetta Milkcheese Sheeps Mini Tin", price: 0, sku: "10178", category: "DIARY" },
  { name: "Fettuccine Pasta", price: 0, sku: "10179", category: "PASTA" },
  { name: "Flax Brown Seeds", price: 0, sku: "10180", category: "PANTRY" },
  { name: "Flourpremimum Mul", price: 0, sku: "10181", category: "HOT & COLD SECTION" },
  { name: "Food Colour Red/Yellow", price: 0, sku: "10182", category: "HOT & COLD SECTION" },
  { name: "Forsan Pepper Jack Cheese Slice", price: 0, sku: "10183", category: "CHEESE & BUTTER" },
  { name: "Foul Medammes Can", price: 0, sku: "10184", category: "HOT & COLD SECTION" },
  { name: "Free Feta Cheese", price: 0, sku: "10185", category: "DIARY" },
  { name: "Freekah Rice", price: 0, sku: "10186", category: "RICE" },
  { name: "Fried Onion", price: 0, sku: "10187", category: "HOT & COLD SECTION" },
  { name: "Frozen Brocolli", price: 0, sku: "10188", category: "FROZEN VEG&FRUITS" },
  { name: "Frozen Green Beans", price: 0, sku: "10189", category: "FROZEN VEG&FRUITS" },
  { name: "Frozen Strawberry", price: 0, sku: "10190", category: "FROZEN VEG&FRUITS" },
  { name: "Fusilli Pasta Brown", price: 0, sku: "10191", category: "PASTA" },
  { name: "Fusilli White", price: 0, sku: "10192", category: "PASTA" },
  { name: "Garam Masala", price: 0, sku: "10193", category: "SPICES" },
  { name: "Garlic", price: 0, sku: "10194", category: "FRUIT & VEGETABLES" },
  { name: "Garlic Powder", price: 0, sku: "10195", category: "SPICES" },
  { name: "Gelatine", price: 0, sku: "10196", category: "HOT & COLD SECTION" },
  { name: "Ginger", price: 0, sku: "10197", category: "FRUIT & VEGETABLES" },
  { name: "Ginger Garlic Paste", price: 0, sku: "10198", category: "HOT & COLD SECTION" },
  { name: "Ginger Powder", price: 0, sku: "10199", category: "SPICES" },
  { name: "Goat Cheese (Lexquis)", price: 0, sku: "10200", category: "CHEESE & BUTTER" },
  { name: "Gouda Cheese Slices", price: 0, sku: "10201", category: "CHEESE & BUTTER" },
  { name: "Grandmas Molasses", price: 0, sku: "10202", category: "SAUCE & VINEGAR" },
  { name: "Greek Yoghurt", price: 0, sku: "10203", category: "DIARY" },
  { name: "Green Apple", price: 0, sku: "10204", category: "FRUIT & VEGETABLES" },
  { name: "Green Beans", price: 0, sku: "10205", category: "FRUIT & VEGETABLES" },
  { name: "Green Capsicum", price: 0.600, sku: "10206", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Green Chili", price: 0, sku: "10207", category: "FRUIT & VEGETABLES" },
  { name: "Green Lentil Whole", price: 0, sku: "10208", category: "HOT & COLD SECTION" },
  { name: "Green Olive Slice", price: 0, sku: "10209", category: "HOT & COLD SECTION" },
  { name: "Green Peas Frozen", price: 0, sku: "10210", category: "FROZEN VEG&FRUITS" },
  { name: "Ground Beef", price: 0, sku: "10211", category: "MEAT" },
  { name: "Halloumi Cheese Light", price: 0, sku: "10212", category: "CHEESE & BUTTER" },
  { name: "Hamour Fillet Frozen", price: 0, sku: "10213", category: "SEAFOOD" },
  { name: "Hoisin Sauce", price: 0, sku: "10214", category: "SAUCE & VINEGAR" },
  { name: "Honey", price: 0, sku: "10215", category: "BAKERY" },
  { name: "Honey Bottle Small", price: 0, sku: "10216", category: "NON FOOD - PACKING" },
  { name: "Ice Burg Lettuce", price: 0, sku: "10217", category: "FRUIT & VEGETABLES" },
  { name: "Icing Sugar", price: 0, sku: "10218", category: "SUGAR" },
  { name: "Ispagul Husk", price: 0, sku: "10219", category: "BAKERY" },
  { name: "Jalapeno", price: 0, sku: "10221", category: "HOT & COLD SECTION" },
  { name: "Kalamata Oilives", price: 0, sku: "10222", category: "HOT & COLD SECTION" },
  { name: "Kale", price: 0, sku: "10223", category: "FRUIT & VEGETABLES" },
  { name: "Kalibo Dark Chocolate", price: 0, sku: "10224", category: "BAKERY" },
  { name: "Kasturi Methi", price: 0, sku: "10225", category: "SPICES" },
  { name: "Ketchup", price: 0, sku: "10226", category: "HOT & COLD SECTION" },
  { name: "Kilbo White Chooclate", price: 0, sku: "10227", category: "BAKERY" },
  { name: "Kiwi", price: 0, sku: "10228", category: "FRUIT & VEGETABLES" },
  { name: "Kunafa", price: 0, sku: "10229", category: "BAKERY" },
  { name: "Laban", price: 0, sku: "10230", category: "DIARY" },
  { name: "Labneh", price: 0, sku: "10231", category: "DIARY" },
  { name: "Labneh Light", price: 0, sku: "10232", category: "DIARY" },
  { name: "Lady Finger Biscuits", price: 0, sku: "10233", category: "BAKERY" },
  { name: "Lamb Fat", price: 0, sku: "10234", category: "MEAT" },
  { name: "Lamb Meat", price: 0, sku: "10235", category: "MEAT" },
  { name: "Lasagne Pasta White", price: 0, sku: "10236", category: "PASTA" },
  { name: "Lavender", price: 0, sku: "10237", category: "BAKERY" },
  { name: "Leeks", price: 0, sku: "10238", category: "FRUIT & VEGETABLES" },
  { name: "Lemon", price: 0, sku: "10239", category: "FRUIT & VEGETABLES" },
  { name: "Lemon Gras", price: 0, sku: "10240", category: "FRUIT & VEGETABLES" },
  { name: "Lemon Juice", price: 0, sku: "10241", category: "HOT & COLD SECTION" },
  { name: "Lemon Salt", price: 0, sku: "10242", category: "HOT & COLD SECTION" },
  { name: "Lettuce Frisse", price: 0, sku: "10243", category: "FRUIT & VEGETABLES" },
  { name: "Lettuce Lolo Blando", price: 0, sku: "10244", category: "FRUIT & VEGETABLES" },
  { name: "Lime", price: 0.372, sku: "10245", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Linguine Pasta Inchgranoro", price: 0, sku: "10246", category: "PASTA" },
  { name: "Lipton Tea Yellow", price: 0, sku: "10247", category: "HOT & COLD SECTION" },
  { name: "Lolorosso Lettuce", price: 0, sku: "10248", category: "FRUIT & VEGETABLES" },
  { name: "Lotus Crumbs", price: 0, sku: "10249", category: "BAKERY" },
  { name: "Lotus Topping", price: 0, sku: "10250", category: "BAKERY" },
  { name: "Low Fat Mayonaise-Gsf Uae", price: 0, sku: "10251", category: "HOT & COLD SECTION" },
  { name: "Low Sodium Soya Sauce", price: 0, sku: "10252", category: "SAUCE & VINEGAR" },
  { name: "Lubeca Finest Milk Chooclaate", price: 0, sku: "10253", category: "BAKERY" },
  { name: "Macroni", price: 0, sku: "10254", category: "PASTA" },
  { name: "Madras Curry Powder", price: 0, sku: "10255", category: "SPICES" },
  { name: "Maggi Demiglace", price: 0, sku: "10256", category: "HOT & COLD SECTION" },
  { name: "Magic Seasoning Salt", price: 0, sku: "10257", category: "HOT & COLD SECTION" },
  { name: "Maize Starch Corn Flour", price: 0, sku: "10258", category: "BAKERY" },
  { name: "Makdous", price: 0, sku: "10259", category: "HOT & COLD SECTION" },
  { name: "Manchego Cheese", price: 0, sku: "10260", category: "CHEESE & BUTTER" },
  { name: "Mango", price: 0, sku: "10261", category: "FRUIT & VEGETABLES" },
  { name: "Mango Chutney", price: 0, sku: "10262", category: "HOT & COLD SECTION" },
  { name: "Mango Frozen", price: 0, sku: "10263", category: "FROZEN VEG&FRUITS" },
  { name: "Mango Kyni", price: 0, sku: "10264", category: "FRUIT & VEGETABLES" },
  { name: "Mango Puree Frozen Ponthier Inch", price: 0, sku: "10265", category: "HOT & COLD SECTION" },
  { name: "Mango Tymor", price: 0, sku: "10266", category: "FRUIT & VEGETABLES" },
  { name: "Maple Syrup", price: 0, sku: "10267", category: "BAKERY" },
  { name: "Mascarpone", price: 0, sku: "10268", category: "DIARY" },
  { name: "Masoor Dal", price: 0, sku: "10269", category: "HOT & COLD SECTION" },
  { name: "Meat Spices", price: 0, sku: "10270", category: "SPICES" },
  { name: "Melon-Cantaloup (Sweet Melon)", price: 0, sku: "10271", category: "FRUIT & VEGETABLES" },
  { name: "Microgreen - Mustard", price: 0, sku: "10272", category: "FRUIT & VEGETABLES" },
  { name: "Microgreen - Radish", price: 0.075, sku: "10273", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Milk Chocolate", price: 0, sku: "10274", category: "BAKERY" },
  { name: "Milk Chocolate Kargil", price: 0, sku: "10275", category: "BAKERY" },
  { name: "Milk Full Fat", price: 0, sku: "10276", category: "DIARY" },
  { name: "Milk Low Fat", price: 0, sku: "10277", category: "DIARY" },
  { name: "Milk Powder", price: 0, sku: "10278", category: "BAKERY" },
  { name: "Mint", price: 0, sku: "10279", category: "FRUIT & VEGETABLES" },
  { name: "Mix Quinoa", price: 0, sku: "10280", category: "HOT & COLD SECTION" },
  { name: "Mixed Spicy Seasoning", price: 0, sku: "10281", category: "SPICES" },
  { name: "Molokia Frozen", price: 0, sku: "10282", category: "FROZEN VEG&FRUITS" },
  { name: "Mozzarella Cheese", price: 0, sku: "10283", category: "CHEESE & BUTTER" },
  { name: "Multicereal Brown Ciabatta", price: 0, sku: "10284", category: "BREAD" },
  { name: "Multicereal Burger Bun", price: 0, sku: "10285", category: "BREAD" },
  { name: "Mushroom Can", price: 0, sku: "10286", category: "HOT & COLD SECTION" },
  { name: "Mustard Oil", price: 0, sku: "10287", category: "OIL" },
  { name: "Mustard Seeds", price: 0, sku: "10288", category: "SPICES" },
  { name: "Mutton Leg Boneless", price: 0, sku: "10289", category: "MEAT" },
  { name: "Nestle Fitness", price: 0, sku: "10290", category: "HOT & COLD SECTION" },
  { name: "Nutmeg Powder", price: 0, sku: "10291", category: "SPICES" },
  { name: "Nutritional Yeast", price: 0, sku: "10292", category: "BAKERY" },
  { name: "Nzmp Unsalted Creamy Butter", price: 0, sku: "10293", category: "BAKERY" },
  { name: "Oat Flour Whole Grain Redmll", price: 0, sku: "10294", category: "BAKERY" },
  { name: "Oats Whole Jar", price: 0, sku: "10295", category: "BAKERY" },
  { name: "Okra", price: 0, sku: "10296", category: "FROZEN VEG&FRUITS" },
  { name: "Olive Oil", price: 0, sku: "10297", category: "OIL" },
  { name: "Olive Oil Syrian Virgin", price: 0, sku: "10298", category: "OIL" },
  { name: "Onion Powder", price: 0, sku: "10299", category: "SPICES" },
  { name: "Orange", price: 0, sku: "10300", category: "FRUIT & VEGETABLES" },
  { name: "Orange Juice", price: 0, sku: "10301", category: "BAKERY" },
  { name: "Oregano", price: 0, sku: "10302", category: "FRUIT & VEGETABLES" },
  { name: "Oyster Sauce", price: 0, sku: "10303", category: "SAUCE & VINEGAR" },
  { name: "Paprika Powder", price: 0, sku: "10304", category: "SPICES" },
  { name: "Parmesan Cheese Block", price: 0, sku: "10305", category: "CHEESE & BUTTER" },
  { name: "Parsley", price: 0, sku: "10306", category: "FRUIT & VEGETABLES" },
  { name: "Pasta Fusili", price: 0, sku: "10307", category: "PASTA" },
  { name: "Pasta Macaroni", price: 0, sku: "10308", category: "PASTA" },
  { name: "Pasta Macaroni Eblows", price: 0, sku: "10309", category: "PASTA" },
  { name: "Pasta Penne Brown", price: 0, sku: "10310", category: "PASTA" },
  { name: "Pasta Penne Rigate", price: 0, sku: "10311", category: "PASTA" },
  { name: "Pasta Shell", price: 0, sku: "10312", category: "PASTA" },
  { name: "Pasta Spaghetti Brown Nature Land", price: 0, sku: "10313", category: "PASTA" },
  { name: "Pasta Spaghetti White", price: 0, sku: "10314", category: "PASTA" },
  { name: "Pasta-Orzo", price: 0, sku: "10315", category: "PASTA" },
  { name: "Peanut Butter", price: 0, sku: "10316", category: "BAKERY" },
  { name: "Peanut Oil", price: 0, sku: "10317", category: "OIL" },
  { name: "Peanut White Raw", price: 0, sku: "10318", category: "PANTRY" },
  { name: "Pecan Nuts", price: 0, sku: "10319", category: "PANTRY" },
  { name: "Peeled Tomatoes", price: 0, sku: "10320", category: "HOT & COLD SECTION" },
  { name: "Pine Seeds", price: 0, sku: "10321", category: "PANTRY" },
  { name: "Pineapple Gold", price: 0, sku: "10322", category: "FRUIT & VEGETABLES" },
  { name: "Pistacho Nuts", price: 0, sku: "10323", category: "PANTRY" },
  { name: "Pistacho Powder", price: 0, sku: "10324", category: "PANTRY" },
  { name: "Pomegranate", price: 0, sku: "10325", category: "FRUIT & VEGETABLES" },
  { name: "Pomegranate Molasses Bottle", price: 0, sku: "10326", category: "SAUCE & VINEGAR" },
  { name: "Pomelo", price: 0, sku: "10327", category: "FRUIT & VEGETABLES" },
  { name: "Portobello Mashroom", price: 0, sku: "10328", category: "FRUIT & VEGETABLES" },
  { name: "Potato", price: 0, sku: "10329", category: "FRUIT & VEGETABLES" },
  { name: "Potato Bun 2.5 Inch", price: 0, sku: "10330", category: "BREAD" },
  { name: "Potato Wedges Seasoned Skin On", price: 0, sku: "10331", category: "BREAD" },
  { name: "President Cream Cheese", price: 0, sku: "10332", category: "CHEESE & BUTTER" },
  { name: "Pretzel", price: 0, sku: "10333", category: "BAKERY" },
  { name: "Protein Powder", price: 0, sku: "10334", category: "BAKERY" },
  { name: "Pumpkin", price: 0, sku: "10335", category: "FRUIT & VEGETABLES" },
  { name: "Pumpkin Seed", price: 0, sku: "10336", category: "PANTRY" },
  { name: "Purple Cabbage", price: 0, sku: "10337", category: "FRUIT & VEGETABLES" },
  { name: "Yellow Carrot", price: 0, sku: "10338", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Purple Potato", price: 0, sku: "10339", category: "FRUIT & VEGETABLES" },
  { name: "Radicchio", price: 0, sku: "10340", category: "FRUIT & VEGETABLES" },
  { name: "Radish", price: 0, sku: "10341", category: "FRUIT & VEGETABLES" },
  { name: "Raisin Silk", price: 0, sku: "10342", category: "PANTRY" },
  { name: "Rasberry", price: 0, sku: "10343", category: "FRUIT & VEGETABLES" },
  { name: "Red Apple", price: 0, sku: "10344", category: "FRUIT & VEGETABLES" },
  { name: "Red Berry", price: 0, sku: "10345", category: "FRUIT & VEGETABLES" },
  { name: "Red Cabage", price: 0, sku: "10346", category: "FRUIT & VEGETABLES" },
  { name: "Red Capsicum", price: 0, sku: "10347", category: "FRUIT & VEGETABLES" },
  { name: "Red Carrot", price: 0, sku: "10348", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Red Chili Hot", price: 0, sku: "10349", category: "FRUIT & VEGETABLES" },
  { name: "Red Chili Powder", price: 0, sku: "10350", category: "SPICES" },
  { name: "Red Chilli Flakes", price: 0, sku: "10351", category: "SPICES" },
  { name: "Red Currant", price: 0, sku: "10352", category: "FRUIT & VEGETABLES" },
  { name: "Red Grape", price: 0, sku: "10353", category: "FRUIT & VEGETABLES" },
  { name: "Red Kidney Beans Tin", price: 0, sku: "10354", category: "HOT & COLD SECTION" },
  { name: "Red Lentil Masor Dal", price: 0, sku: "10355", category: "HOT & COLD SECTION" },
  { name: "Red Nescafe", price: 0, sku: "10356", category: "BAKERY" },
  { name: "Red Onion", price: 0, sku: "10357", category: "FRUIT & VEGETABLES" },
  { name: "Red Quinoa", price: 0, sku: "10358", category: "HOT & COLD SECTION" },
  { name: "Red Raddish", price: 0, sku: "10359", category: "FRUIT & VEGETABLES" },
  { name: "Rice Crispy", price: 0, sku: "10360", category: "BAKERY" },
  { name: "Rice Flour", price: 0, sku: "10361", category: "FLOUR" },
  { name: "Rice Mixture", price: 0, sku: "10362", category: "RICE" },
  { name: "Rice Noodles", price: 0, sku: "10363", category: "PASTA" },
  { name: "Rice Vinigar", price: 0, sku: "10364", category: "SAUCE & VINEGAR" },
  { name: "Rigatoni Pasta Ottima", price: 0, sku: "10365", category: "PASTA" },
  { name: "Rocca", price: 0, sku: "10366", category: "FRUIT & VEGETABLES" },
  { name: "Romaine Lettuce", price: 0, sku: "10367", category: "FRUIT & VEGETABLES" },
  { name: "Rose Buds", price: 0, sku: "10368", category: "BAKERY" },
  { name: "Rose Water", price: 0, sku: "10369", category: "BAKERY" },
  { name: "Rosemary", price: 0, sku: "10370", category: "FRUIT & VEGETABLES" },
  { name: "Safron", price: 0, sku: "10371", category: "BAKERY" },
  { name: "Salmon Fillet", price: 0, sku: "10372", category: "SEAFOOD" },
  { name: "Salt", price: 0, sku: "10373", category: "HOT & COLD SECTION" },
  { name: "Sea Bass Fillet", price: 0, sku: "10374", category: "SEAFOOD" },
  { name: "Sea Salt", price: 0, sku: "10375", category: "HOT & COLD SECTION" },
  { name: "Semolina", price: 0, sku: "10376", category: "BAKERY" },
  { name: "Sera Hot Pepper Paste", price: 0, sku: "10377", category: "SAUCE & VINEGAR" },
  { name: "Sesame Oil", price: 0, sku: "10378", category: "OIL" },
  { name: "Sesame Seed Black", price: 0, sku: "10379", category: "HOT & COLD SECTION" },
  { name: "Sesame Seed White", price: 0, sku: "10380", category: "HOT & COLD SECTION" },
  { name: "Shawerma Spice", price: 0, sku: "10381", category: "SPICES" },
  { name: "Shrimp Pd", price: 0, sku: "10382", category: "SEAFOOD" },
  { name: "Skimmed Milk", price: 0, sku: "10383", category: "DIARY" },
  { name: "Smoked Turkey Breast", price: 0, sku: "10384", category: "MEAT" },
  { name: "Snow Beans", price: 0, sku: "10385", category: "FROZEN VEG&FRUITS" },
  { name: "Soft Cream Cheese Anchor", price: 0, sku: "10386", category: "CHEESE & BUTTER" },
  { name: "Sour Cream", price: 3.500, sku: "10387", category: "DIARY", unit: "kg" },
  { name: "Sour Dough Bread", price: 0, sku: "10388", category: "BREAD" },
  { name: "Soya Bean Oil", price: 0, sku: "10389", category: "OIL" },
  { name: "Soya Milk", price: 0, sku: "10390", category: "DIARY" },
  { name: "Spinach", price: 0, sku: "10391", category: "FRUIT & VEGETABLES" },
  { name: "Spinach Frozen", price: 0, sku: "10392", category: "FROZEN VEG&FRUITS" },
  { name: "Spring Onion", price: 0, sku: "10393", category: "FRUIT & VEGETABLES" },
  { name: "Sprout", price: 0, sku: "10394", category: "FRUIT & VEGETABLES" },
  { name: "Sprout Beans", price: 0, sku: "10395", category: "FRUIT & VEGETABLES" },
  { name: "Sriracha Hot Chilli", price: 0, sku: "10396", category: "SAUCE & VINEGAR" },
  { name: "Star Anise Powder", price: 0, sku: "10397", category: "SPICES" },
  { name: "Steak Sauce Fairco", price: 0, sku: "10398", category: "SAUCE & VINEGAR" },
  { name: "Stevia", price: 0, sku: "10399", category: "BAKERY" },
  { name: "Strawberry", price: 0, sku: "10400", category: "FRUIT & VEGETABLES" },
  { name: "Strawberry Filling", price: 0, sku: "10401", category: "BAKERY" },
  { name: "Strawberry Jam & Fig Jam", price: 0, sku: "10402", category: "JAM" },
  { name: "Strawberry Powder", price: 0, sku: "10403", category: "BAKERY" },
  { name: "Sugar", price: 0, sku: "10404", category: "SUGAR" },
  { name: "Sugar Free Arabic Sweet Syrup", price: 0, sku: "10405", category: "BAKERY" },
  { name: "Sukri Dates Yellow", price: 0, sku: "10406", category: "BAKERY" },
  { name: "Summak Powder", price: 0, sku: "10407", category: "SPICES" },
  { name: "Sun Flower Oil", price: 0, sku: "10408", category: "OIL" },
  { name: "Sundried Tomatoes", price: 0, sku: "10409", category: "HOT & COLD SECTION" },
  { name: "Sunflower Seed", price: 0, sku: "10410", category: "PANTRY" },
  { name: "Sweet Chilly Sauce Bottle", price: 0, sku: "10411", category: "SAUCE & VINEGAR" },
  { name: "Sweet Corn", price: 0, sku: "10412", category: "HOT & COLD SECTION" },
  { name: "Sweet Potato", price: 0, sku: "10413", category: "HOT & COLD SECTION" },
  { name: "Sweet Potato Fries", price: 0, sku: "10414", category: "HOT & COLD SECTION" },
  { name: "T65 Flour", price: 0, sku: "10415", category: "FLOUR" },
  { name: "Taco Seasoning", price: 0, sku: "10416", category: "SPICES" },
  { name: "Taco Shell", price: 0, sku: "10417", category: "SPICES" },
  { name: "Tahina", price: 0, sku: "10418", category: "SAUCE & VINEGAR" },
  { name: "Tamarind", price: 0, sku: "10419", category: "HOT & COLD SECTION" },
  { name: "Tamarind Sauce", price: 0, sku: "10420", category: "SAUCE & VINEGAR" },
  { name: "Tandoori Masala", price: 0, sku: "10421", category: "SPICES" },
  { name: "Teriyaki Sauce", price: 0, sku: "10422", category: "SAUCE & VINEGAR" },
  { name: "Thai Green Curry Paste", price: 0, sku: "10423", category: "HOT & COLD SECTION" },
  { name: "Thai Red Curry Paste", price: 0, sku: "10424", category: "HOT & COLD SECTION" },
  { name: "Thick Cream", price: 0, sku: "10425", category: "DIARY" },
  { name: "Thyme", price: 0, sku: "10426", category: "FRUIT & VEGETABLES" },
  { name: "Tikka Masala", price: 0, sku: "10427", category: "SPICES" },
  { name: "Tilapia Fillets", price: 0, sku: "10428", category: "SEAFOOD" },
  { name: "Toast Bread Gulten Free", price: 0, sku: "10429", category: "BREAD" },
  { name: "Tofu Firm", price: 0, sku: "10430", category: "HOT & COLD SECTION" },
  { name: "Tomato", price: 0, sku: "10431", category: "FRUIT & VEGETABLES" },
  { name: "Tomato Paste", price: 0, sku: "10432", category: "HOT & COLD SECTION" },
  { name: "Topi Cheese (Ball)", price: 0, sku: "10433", category: "CHEESE & BUTTER" },
  { name: "Truffle Oil", price: 0, sku: "10434", category: "OIL" },
  { name: "Tuna Fish", price: 0, sku: "10435", category: "SEAFOOD" },
  { name: "Turmeric Powder", price: 0, sku: "10436", category: "SPICES" },
  { name: "Turnip Pickle Gallon", price: 0, sku: "10437", category: "HOT & COLD SECTION" },
  { name: "Vanilla Powder", price: 0, sku: "10438", category: "HOT & COLD SECTION" },
  { name: "Vegetable Maggi Cube", price: 0, sku: "10439", category: "HOT & COLD SECTION" },
  { name: "Vegetable Magic Powder", price: 0, sku: "10440", category: "HOT & COLD SECTION" },
  { name: "Vermcelli / Filini-N.107", price: 0, sku: "10441", category: "HOT & COLD SECTION" },
  { name: "Vermicelli Egg Noodles Thai", price: 0, sku: "10442", category: "PASTA" },
  { name: "Vine Leaves Martexpo", price: 0, sku: "10443", category: "HOT & COLD SECTION" },
  { name: "Walnut", price: 0, sku: "10444", category: "PANTRY" },
  { name: "Water Melon", price: 0, sku: "10445", category: "FRUIT & VEGETABLES" },
  { name: "Wheat Flour Whole", price: 0, sku: "10446", category: "FLOUR" },
  { name: "Wheat Gluten Flour", price: 0, sku: "10447", category: "FLOUR" },
  { name: "Whipping Cream 6X1L", price: 0, sku: "10448", category: "DIARY" },
  { name: "White Beans In Tin", price: 0, sku: "10449", category: "HOT & COLD SECTION" },
  { name: "White Cabbage", price: 0, sku: "10450", category: "FRUIT & VEGETABLES" },
  { name: "White Coconut Flakes Unsweetened", price: 0, sku: "10451", category: "HOT & COLD SECTION" },
  { name: "White Flour", price: 0, sku: "10452", category: "FLOUR" },
  { name: "White Mashroom", price: 0, sku: "10453", category: "FRUIT & VEGETABLES" },
  { name: "White Miso", price: 0, sku: "10454", category: "HOT & COLD SECTION" },
  { name: "White Onion", price: 0, sku: "10455", category: "FRUIT & VEGETABLES" },
  { name: "White Pepper", price: 0, sku: "10456", category: "SPICES" },
  { name: "White Pepper Powder", price: 0, sku: "10457", category: "SPICES" },
  { name: "White Quinoa", price: 0, sku: "10458", category: "HOT & COLD SECTION" },
  { name: "White Vinegar", price: 0, sku: "10459", category: "SAUCE & VINEGAR" },
  { name: "Whole Grain Mustard", price: 0, sku: "10460", category: "HOT & COLD SECTION" },
  { name: "Whole Wheat Penne Naturland", price: 0, sku: "10461", category: "PASTA" },
  { name: "Wild Rice", price: 0, sku: "10462", category: "RICE" },
  { name: "Wilton White Rolled Fondant", price: 0, sku: "10463", category: "BAKERY" },
  { name: "Worcestershire Sauce", price: 0, sku: "10464", category: "SAUCE & VINEGAR" },
  { name: "Yellow Burgul Fine", price: 0, sku: "10465", category: "BAKERY" },
  { name: "Yellow Capsicum", price: 0, sku: "10466", category: "FRUIT & VEGETABLES" },
  { name: "Yellow Caroot", price: 0, sku: "10467", category: "FRUIT & VEGETABLES" },
  { name: "Yellow Mustard", price: 0, sku: "10468", category: "FRUIT & VEGETABLES" },
  { name: "Yoghurt", price: 0, sku: "10469", category: "DIARY" },
  { name: "Zatar", price: 0, sku: "10470", category: "FRUIT & VEGETABLES" },
  { name: "Ziti Rigate", price: 0, sku: "10471", category: "PASTA" },
  { name: "Zucchini", price: 0, sku: "10472", category: "FRUIT & VEGETABLES" },
  { name: "Zucchini - Yellow", price: 0, sku: "10473", category: "FRUIT & VEGETABLES" },
  { name: "10 Oz Pet Ice cream Cup", price: 0, sku: "10474", category: "NON FOOD - PACKING" },
  { name: "1Oz Pet Portion Cup W/Lid", price: 0, sku: "10475", category: "NON FOOD - PACKING" },
  { name: "2Oz Pet Portion Cup", price: 0, sku: "10476", category: "NON FOOD - PACKING" },
  { name: "2Oz Pet Portion Cup W/Lid", price: 0, sku: "10477", category: "NON FOOD - PACKING" },
  { name: "6 Oz Iceceram Cup", price: 0, sku: "10478", category: "NON FOOD - PACKING" },
  { name: "6 Oz Rect Sugar Can", price: 0, sku: "10479", category: "NON FOOD - PACKING" },
  { name: "750Ml Rect Sugar Cane W/Lid Clr", price: 0, sku: "10481", category: "NON FOOD - PACKING" },
  { name: "8 Inch Brown Tortilla (Pkt 6Pcs)", price: 0, sku: "10482", category: "NON FOOD - PACKING" },
  { name: "8 Inch White Tortilla (Pkt 6Pcs)", price: 0, sku: "10483", category: "NON FOOD - PACKING" },
  { name: "850Ml Rect Sugar Cane W/Lid Clr", price: 0, sku: "10484", category: "NON FOOD - PACKING" },
  { name: "Burger Container Sugar Can Sandwich Box", price: 0, sku: "10485", category: "NON FOOD - PACKING" },
  { name: "Clear Container 6 Oz (S95)", price: 0, sku: "10486", category: "NON FOOD - PACKING" },
  { name: "Clear Sauce Cup 4 Oz", price: 0, sku: "10487", category: "NON FOOD - PACKING" },
  { name: "Inner Tray For Salad 10 Oz.", price: 0, sku: "10488", category: "NON FOOD - PACKING" },
  { name: "M/W Black Rect.Container W/Lid - 1*150Pcs - 16Oz", price: 0, sku: "10489", category: "NON FOOD - PACKING" },
  { name: "M/W Black Rect.Container W/Lid - 1*150Pcs - 32Oz", price: 0, sku: "10490", category: "NON FOOD - PACKING" },
  { name: "Re232 2 Compartment", price: 0, sku: "10491", category: "NON FOOD - PACKING" },
  { name: "Re24", price: 0, sku: "10492", category: "NON FOOD - PACKING" },
  { name: "Re28", price: 0, sku: "10493", category: "NON FOOD - PACKING" },
  { name: "Rect, Clear Cont 12 Oz", price: 0, sku: "10494", category: "NON FOOD - PACKING" },
  { name: "Rect, Clear Cont 24 Oz", price: 0, sku: "10495", category: "NON FOOD - PACKING" },
  { name: "Round Clear M/W Contr W/Lid 9Oz -1*20*50 Pcs", price: 0, sku: "10496", category: "NON FOOD - PACKING" },
  { name: "Square Cleared Hinged Box 1*50*4 Pkt -16Oz 600 Ml", price: 0, sku: "10497", category: "NON FOOD - PACKING" },
  { name: "Triangle Sandwich Wedge Double Swc80", price: 0, sku: "10498", category: "NON FOOD - PACKING" },
  { name: "Taco Bread", price: 0.033, sku: "10499", category: "BREAD", unit: "kg" },
  { name: "Apple Juice", price: 0, sku: "psk-001", category: "COLD DRINKS" },
  { name: "Be Real", price: 0, sku: "psk-003", category: "COLD DRINKS" },
  { name: "Chanel Orange", price: 0, sku: "psk-005", category: "COLD DRINKS" },
  { name: "Cold Brew", price: 0, sku: "psk-006", category: "COLD DRINKS" },
  { name: "Green Light", price: 0, sku: "psk-009", category: "COLD DRINKS" },
  { name: "Purple Rain", price: 0, sku: "psk-012", category: "COLD DRINKS" },
  { name: "Rose Lemonade", price: 0, sku: "psk-013", category: "COLD DRINKS" },
  { name: "Sparkling Water", price: 0, sku: "psk-015", category: "COLD DRINKS" },
  { name: "The Roots", price: 0, sku: "psk-016", category: "COLD DRINKS" },
  { name: "Cashew Crunch", price: 0, sku: "psk-020", category: "GATHERING" },
  { name: "Chocolate Cashew Butter (42 Pcs)", price: 0, sku: "psk-022", category: "GATHERING" },
  { name: "Dips Box - Large", price: 0, sku: "psk-023", category: "GATHERING" },
  { name: "Dips Box - Medium", price: 0, sku: "psk-024", category: "GATHERING" },
  { name: "Whole Flourless Chocolate Cake", price: 0, sku: "psk-026", category: "GATHERING" }
];

// Continue with remaining data...
const moreRawMaterialsData = [
  { name: "Heartbeet", price: 0, sku: "psk-027", category: "GATHERING" },
  { name: "Juice Box (12 X 250Ml)", price: 0, sku: "psk-028", category: "GATHERING" },
  { name: "Peanut Butter Dates (36 Pcs)", price: 0, sku: "psk-034", category: "GATHERING" },
  { name: "Sweetgreen", price: 0, sku: "psk-040", category: "GATHERING" },
  { name: "Vegan Chocolate Truffles (42 Pcs)", price: 0, sku: "psk-041", category: "GATHERING" },
  { name: "Whole Vegan Kunafa", price: 0, sku: "psk-042", category: "GATHERING" },
  { name: "Caribbean Chicken", price: 0, sku: "psk-044", category: "GLUTEN-FREE TACOS & PIZZA", unit: "kg" },
  { name: "Grilled Steak", price: 0, sku: "psk-045", category: "GLUTEN-FREE TACOS & PIZZA" },
  { name: "Shrimp Sriracha", price: 0, sku: "psk-051", category: "GLUTEN-FREE TACOS & PIZZA" },
  { name: "Vegan Portobello With Cilantro Sauce", price: 0, sku: "psk-052", category: "GLUTEN-FREE TACOS & PIZZA" },
  { name: "Banana Pudding", price: 0, sku: "psk-053", category: "HAPPY ENDINGS" },
  { name: "Carrot Cake (Vegan - Gf)", price: 0, sku: "psk-054", category: "HAPPY ENDINGS" },
  { name: "Chocolate Cashew Butter", price: 0, sku: "psk-057", category: "HAPPY ENDINGS" },
  { name: "Chocolate Cookies", price: 0, sku: "psk-058", category: "HAPPY ENDINGS" },
  { name: "Chocolate Pudding", price: 0, sku: "psk-059", category: "HAPPY ENDINGS" },
  { name: "Date Square", price: 0, sku: "psk-060", category: "HAPPY ENDINGS" },
  { name: "Flourless Chocolate Cake", price: 0, sku: "psk-061", category: "HAPPY ENDINGS" },
  { name: "Granola Truffle", price: 0, sku: "psk-062", category: "HAPPY ENDINGS" },
  { name: "Kunafa (Gf-Vegan)", price: 0, sku: "psk-063", category: "HAPPY ENDINGS" },
  { name: "Kunafa Cheesecake", price: 0, sku: "psk-064", category: "HAPPY ENDINGS" },
  { name: "Kunafa Cheesecake Gathering", price: 0, sku: "psk-0653", category: "RAMADAN" },
  { name: "Mix Fruit Salad", price: 0, sku: "psk-067", category: "HAPPY ENDINGS" },
  { name: "Peanut Butter Dates", price: 0, sku: "psk-068", category: "HAPPY ENDINGS" },
  { name: "Pecan Pie Truffles", price: 0, sku: "psk-069", category: "HAPPY ENDINGS" },
  { name: "Tahini Sesame Dates", price: 0, sku: "psk-070", category: "HAPPY ENDINGS" },
  { name: "Vegan Chocolate Truffles", price: 0, sku: "psk-073", category: "HAPPY ENDINGS" },
  { name: "Vegan Kunafa", price: 0, sku: "psk-074", category: "HAPPY ENDINGS" },
  { name: "Breakfast Box", price: 0, sku: "psk-075", category: "OFFERS" },
  { name: "Cumin Cashew - 200G", price: 0, sku: "psk-079", category: "PANTRY BAGS" },
  { name: "Gluten-Free Baked Tortilla Chips", price: 0, sku: "psk-080", category: "PANTRY BAGS" },
  { name: "Maple Glazed Crotouns - 200G", price: 0, sku: "psk-082", category: "PANTRY BAGS" },
  { name: "Pumpkin Granola - 200G", price: 0, sku: "psk-083", category: "PANTRY BAGS" },
  { name: "Pumpkin Seeds - 200G", price: 0, sku: "psk-084", category: "PANTRY BAGS" },
  { name: "Salted Kale Chips - 25G", price: 0, sku: "psk-085", category: "PANTRY BAGS" },
  { name: "Spicy Kale Chips - 25G", price: 0, sku: "psk-086", category: "PANTRY BAGS" },
  { name: "Spicy Crotouns - 200G", price: 0, sku: "psk-087", category: "PANTRY BAGS" },
  { name: "Beet Penne", price: 0, sku: "psk-088", category: "PASTA" },
  { name: "Penne Arabiata", price: 0, sku: "psk-089", category: "PASTA" },
  { name: "Spaghetti Bolognese Pasta", price: 0, sku: "psk-090", category: "PASTA" },
  { name: "Turmeric Penne", price: 0, sku: "psk-091", category: "PASTA" },
  { name: "Vegan Spaghetti Bolognese", price: 0, sku: "psk-092", category: "PASTA" },
  { name: "Zucchini Bolognese", price: 0, sku: "psk-093", category: "PASTA" },
  { name: "Create Your Own Salad", price: 0, sku: "psk-096", category: "SALADS" },
  { name: "Heartbeat", price: 0, sku: "psk-098", category: "SALADS" },
  { name: "Sweet Green", price: 0, sku: "psk-104", category: "SALADS" },
  { name: "Almond Chicken Slider", price: 0, sku: "psk-106", category: "SANDWICHES" },
  { name: "Avo Egg Slider", price: 0, sku: "psk-107", category: "SAVORY BITES" },
  { name: "Avo Turkey", price: 0, sku: "psk-108", category: "SANDWICHES" },
  { name: "Breakfast Burrito Wrap", price: 0, sku: "psk-110", category: "SAVORY BITES" },
  { name: "Brisket Shawerma Sandwich", price: 0, sku: "psk-111", category: "SANDWICHES" },
  { name: "Chicken Burrito Wrap", price: 0, sku: "psk-113", category: "SANDWICHES" },
  { name: "Chicken Shawerma Sandwich", price: 0, sku: "psk-115", category: "SANDWICHES" },
  { name: "Chipotle Egg Slider", price: 0, sku: "psk-116", category: "SAVORY BITES" },
  { name: "Chipotle Turkey", price: 0, sku: "psk-118", category: "SANDWICHES" },
  { name: "Cranberry& Brie Turkey", price: 0, sku: "psk-119", category: "SANDWICHES" },
  { name: "Pesto Halloumi", price: 0, sku: "psk-121", category: "SANDWICHES" },
  { name: "Portabello Pesto Sandwich", price: 0, sku: "psk-123", category: "SANDWICHES" },
  { name: "Power Trip", price: 0, sku: "psk-124", category: "SANDWICHES" },
  { name: "Sandwich Box", price: 0, sku: "psk-126", category: "SANDWICHES" },
  { name: "Southwest Chicken wrap", price: 0, sku: "psk-128", category: "SANDWICHES" },
  { name: "Steak And Cheese Sandwich", price: 0, sku: "psk-129", category: "SANDWICHES" },
  { name: "The Reformer", price: 0, sku: "psk-131", category: "SANDWICHES" },
  { name: "Tuna Sandwich", price: 0, sku: "psk-132", category: "SANDWICHES" }
];

// Additional items (continuing the pattern - this is getting long, so I'll add a note in the script about the full data)
const finalRawMaterialsData = [
  { name: "Avo Mexican Corn", price: 0, sku: "psk-135", category: "SAVORY BITES" },
  { name: "Avo Smash", price: 0, sku: "psk-136", category: "SAVORY BITES" },
  { name: "Avo Smash With Free-Range Poached Eggs", price: 0, sku: "psk-137", category: "SAVORY BITES" },
  { name: "Blondie", price: 0, sku: "psk-138", category: "SAVORY BITES" },
  { name: "Free-Range Poached Eggs On Toast", price: 0, sku: "psk-139", category: "SAVORY BITES" },
  { name: "Halloumi", price: 0, sku: "psk-140", category: "SAVORY BITES" },
  { name: "Sicily", price: 0, sku: "psk-141", category: "SAVORY BITES" },
  { name: "House Ketchup", price: 0, sku: "psk-143", category: "SIDES" },
  { name: "Salted Crispy Kale", price: 0, sku: "psk-144", category: "SIDES" },
  { name: "Spicy Crispy Kale", price: 0, sku: "psk-145", category: "SIDES" },
  { name: "CruditÃ©s", price: 0, sku: "psk-148", category: "SNACKS" },
  { name: "Gluten Free Nachos", price: 0, sku: "psk-149", category: "SNACKS" },
  { name: "Broccoli N Cheddar", price: 0, sku: "psk-153", category: "SOUPS" },
  { name: "Celery Soup", price: 0, sku: "psk-154", category: "SOUPS" },
  { name: "Vegan Lentil", price: 0, sku: "psk-156", category: "SOUPS" },
  { name: "Wild Mushroom Soup", price: 0, sku: "psk-157", category: "SOUPS" },
  { name: "Whole Grain Oats", price: 0, sku: "psk-158", category: "SWEET BITES" },
  { name: "Chia Pudding", price: 0, sku: "psk-160", category: "SWEET BITES" },
  { name: "Greek Yogurt Parfait", price: 0, sku: "psk-161", category: "SWEET BITES" },
  { name: "House Pancake", price: 0, sku: "psk-162", category: "SWEET BITES" },
  { name: "Labneh & Pomegranate On Toast", price: 0, sku: "psk-163", category: "SWEET BITES" },
  { name: "Saffron Quinoa Pudding (Gf-Vegan)", price: 0, sku: "psk-164", category: "SWEET BITES" },
  { name: "Vegan House Pancake", price: 0, sku: "psk-165", category: "SWEET BITES" },
  { name: "Vegan Waffle", price: 0, sku: "psk-166", category: "SWEET BITES" },
  { name: "Almond Crust Chicken", price: 0, sku: "psk-168", category: "WARM BOWLS" },
  { name: "Buff Baby", price: 0, sku: "psk-170", category: "WARM BOWLS" },
  { name: "Chicken Avocado", price: 0, sku: "psk-171", category: "WARM BOWLS" },
  { name: "Create Your Own Bowl", price: 0, sku: "psk-175", category: "WARM BOWLS" },
  { name: "Grilled Steak With Pomegranate Sauce", price: 0, sku: "psk-176", category: "WARM BOWLS" },
  { name: "Harvest Bowl", price: 0, sku: "psk-177", category: "WARM BOWLS" },
  { name: "Kofta With Freekeh", price: 0, sku: "psk-179", category: "WARM BOWLS" },
  { name: "Mongolian Beef", price: 0, sku: "psk-180", category: "WARM BOWLS" },
  { name: "Salmon Avocado", price: 0, sku: "psk-181", category: "WARM BOWLS" },
  { name: "Salmon Harvest", price: 0, sku: "psk-182", category: "WARM BOWLS" },
  { name: "Shrimp Avocado", price: 0, sku: "psk-183", category: "WARM BOWLS" },
  { name: "Shrimp Curry", price: 0, sku: "psk-184", category: "WARM BOWLS" },
  { name: "Shrimp Harvest", price: 0, sku: "psk-185", category: "WARM BOWLS" },
  { name: "Soul Island", price: 0, sku: "psk-186", category: "WARM BOWLS" },
  { name: "Spicy Chicken With Peanut Sauce", price: 0, sku: "psk-187", category: "WARM BOWLS" },
  { name: "Steak Avocado", price: 0, sku: "psk-189", category: "WARM BOWLS" },
  { name: "Steak Harvest", price: 0, sku: "psk-190", category: "WARM BOWLS" },
  { name: "Beet Booster", price: 0, sku: "psk-192", category: "WELLNESS SHOTS" },
  { name: "Green Booster", price: 0, sku: "psk-193", category: "WELLNESS SHOTS" },
  { name: "Turmeric Ginger", price: 0, sku: "psk-194", category: "WELLNESS SHOTS" },
  { name: "Beet Cheese Tray", price: 0, sku: "psk-195", category: "GATHERING" },
  { name: "Small Cheese Tray", price: 0, sku: "psk-196", category: "GATHERING" },
  { name: "Basic Cheese Tray", price: 0, sku: "psk-197", category: "GATHERING" },
  { name: "Detox Water", price: 0, sku: "psk-200", category: "COLD DRINKS" },
  { name: "Honey Mustard Chicken Marinade", price: 0.424, sku: "GEN-HON-I5SR", category: "SPICES", unit: "kg" },
  { name: "Pickled Ginger", price: 0.894, sku: "GEN-PIC-LJ3P", category: "FRUIT & VEGETABLES", unit: "kg" },
  { name: "Caribbean Chicken - 1", price: 7.500, sku: "121212121", category: "CHICKEN", unit: "kg" },
  { name: "Coffe Columbian", price: 0, sku: "GEN-COF-OWFF", category: "BAKERY" },
  { name: "Test Record", price: 0, sku: "GEN-TES-UVRX", category: "BAKERY" },
  { name: "sesame new", price: 0, sku: "GEN-SES-9QRM", category: "SPICES" },
  { name: "KOMPLET SPRAY", price: 1.667, sku: "ML", category: "HOT & COLD SECTION", unit: "kg" },
  { name: "test item - 6-10-25", price: 0, sku: "12121", category: "HOT & COLD SECTION", unit: "kg" }
];

// Combine all data
const allRawMaterials = [...rawMaterialsData, ...moreRawMaterialsData, ...finalRawMaterialsData];

async function seedKuwaitCityRawMaterials() {
  let kuwaitCityConnection;

  try {
    console.log('🚀 Seeding Kuwait City Raw Materials from Spreadsheet');
    console.log('='.repeat(60));
    console.log('');

    // Connect to Kuwait City database
    console.log('🔗 Connecting to Kuwait City database...');
    kuwaitCityConnection = await connectKuwaitCityDB();
    const kuwaitCityModels = initializeKuwaitCityModels(kuwaitCityConnection);
    const KuwaitCityRawMaterial = kuwaitCityModels.KuwaitCityRawMaterial;

    console.log('✅ Connected to Kuwait City database');
    console.log('');

    console.log(`📊 Total items to upload: ${allRawMaterials.length}`);
    console.log('');

    let successCount = 0;
    let errorCount = 0;
    const errors = [];

    // Process each raw material
    for (let i = 0; i < allRawMaterials.length; i++) {
      const item = allRawMaterials[i];
      
      try {
        // Create raw material document
        const rawMaterial = new KuwaitCityRawMaterial({
          materialCode: item.sku,
          materialName: item.name,
          category: 'Raw Materials',
          subCategory: item.category || 'General',
          unitOfMeasure: item.unit || 'unit',
          currentStock: 0, // Initial stock = 0
          minStockLevel: 0,
          maxStockLevel: 1000,
          reorderPoint: 10,
          unitPrice: item.price || 0,
          supplier: 'Default Supplier',
          location: 'Kuwait City Warehouse',
          createdBy: 'System Import',
          updatedBy: 'System Import',
          lastUpdated: new Date()
        });

        await rawMaterial.save();
        successCount++;
        
        if ((i + 1) % 50 === 0) {
          console.log(`   Processed ${i + 1}/${allRawMaterials.length} items...`);
        }
      } catch (error) {
        errorCount++;
        errors.push({
          sku: item.sku,
          name: item.name,
          error: error.message
        });
      }
    }

    console.log('');
    console.log('📊 SEEDING SUMMARY:');
    console.log('='.repeat(60));
    console.log(`   ✅ Successfully uploaded: ${successCount} items`);
    console.log(`   ❌ Failed: ${errorCount} items`);
    console.log(`   📦 Total processed: ${allRawMaterials.length} items`);
    console.log('');

    if (errors.length > 0) {
      console.log('❌ Errors:');
      errors.slice(0, 10).forEach(err => {
        console.log(`   - ${err.sku} (${err.name}): ${err.error}`);
      });
      if (errors.length > 10) {
        console.log(`   ... and ${errors.length - 10} more errors`);
      }
      console.log('');
    }

    return {
      success: true,
      successCount,
      errorCount,
      total: allRawMaterials.length
    };

  } catch (error) {
    console.error('💥 SEEDING FAILED:', error.message);
    console.error('Stack trace:', error.stack);
    return { success: false, message: error.message };
  } finally {
    if (kuwaitCityConnection) {
      await kuwaitCityConnection.close();
      console.log('🔌 Database connection closed');
    }
  }
}

/**
 * Main execution
 */
async function main() {
  try {
    console.log('⚠️  This will upload all raw materials from spreadsheet to Kuwait City database');
    console.log('⚠️  All items will have initial stock quantity = 0');
    console.log('');

    const result = await seedKuwaitCityRawMaterials();
    
    if (result.success) {
      console.log('');
      console.log('🎉 SEEDING COMPLETED SUCCESSFULLY!');
      console.log(`   ✅ ${result.successCount} items uploaded`);
      console.log(`   ❌ ${result.errorCount} items failed`);
    } else {
      console.log('');
      console.log('💥 SEEDING FAILED!');
      console.log(`   Reason: ${result.message}`);
    }
    
  } catch (error) {
    console.error('💥 UNEXPECTED ERROR:', error.message);
    process.exit(1);
  }
}

// Export for use in other scripts
module.exports = {
  seedKuwaitCityRawMaterials
};

// Run if called directly
if (require.main === module) {
  main();
}

